fastlane_version "1.100.0"

default_platform :ios

platform :ios do
  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    match(type: "appstore", readonly: true)
    
    increment_build_number(
      xcodeproj: './ios/{{applicationName}}.xcodeproj'
    )

    ipa = gym(
      scheme: "{{applicationName}}",
      project: "./ios/{{applicationName}}.xcodeproj"
    )

    pilot(ipa: ipa)

    clean_build_artifacts

    commit_version_bump(
      message: "👷 Deployed new version #{lane_context[SharedValues::BUILD_NUMBER]} [skip ci]",
      xcodeproj: './ios/{{applicationName}}.xcodeproj'
    )
  end
end